### ISSUE TITLE
mybatis分页插件文件

### ISSUE THREAD

**Issue by codemonkeykings** [mybatis-book/book#17]
您好，我在项目中需要用到mybatis分页，但是处理过程中遇到了__frch_*_0 字段不存在的问题，由于我对mybatis源码不太了解，鼓捣了半天也没改好，所以想请教一下。我用的mybatis版本是3.4.1

**Comment by abel533** [comment]
分页插件版本是多少？

**Comment by codemonkeykings** [comment]
您好，因为系统中涉及到的分页需求不大，所以我没有使用pager插件，我只是按照网上的代码实现了mybatis提供的Interceptor接口，发现是网上的代码存在问题，其重新生成了BoundSql对象，导致paramterObject信息丢失，所以报错，现在我一改正。谢谢！
