### ISSUE TITLE
通用的Mapper生成器插件，怎样才能不生成注释？

### ISSUE THREAD

**Issue by EwingTsai** [mybatis-book/book#20]
插件类：tk.mybatis.mapper.generator.MapperPlugin
生成的注释示例：
`    
    /**
     * @return USER_ID
     */`
这些注释并不是对所有人都有用，能不能关掉呢？

**Comment by abel533** [comment]
试试`suppressAllComments`。

MBG的详细设置可以参考这里：http://blog.csdn.net/isea533/article/details/42102297

**Comment by EwingTsai** [comment]
MBG的注释已关闭。这个是通用Mapper插件生成的注释，目前还关不了，希望后期可以使用。Thanks！
