### ISSUE TITLE
《MyBatis 从入门到精通》转发送书~~~

### ISSUE THREAD

**Issue by abel533** [mybatis-book/book#4]
## 《MyBatis 从入门到精通》转发送书~~~

京东已经可以直接购买：https://item.jd.com/12103309.html

### 活动说明

根据参与人数进行送书，随机从所有参与人员中抽取几位朋友送书。

当前页面有效参与人数每超过100人，就增加一个送书名额。

**活动时间**：2017年6月30日 至 2017年7月5日(23点59分)，当人数超出300人时提前结束。

结束后会通过直播或者其他方式进行抽奖，抽奖结束后我会联系中奖的朋友。

**为了便于统计，我会删除重复无效的回复，谢谢理解！**

**为了防止图片太大太卡，我稍后会对图片进行处理。**

### 首先关注下方微信公众号。

![default](https://user-images.githubusercontent.com/1787798/27735383-d7f44b2a-5dd1-11e7-8a63-626c2c6e65c9.jpg)

### 进入公众号后，点击菜单【新书购买】

<img src="https://user-images.githubusercontent.com/1787798/27735448-26b7d330-5dd2-11e7-84f9-da5e4b1a8a60.jpg" width="50%"/>

### 点击进入图文消息，转发到朋友圈或QQ空间
<img src="https://user-images.githubusercontent.com/1787798/27735604-12957118-5dd3-11e7-8661-f91c18494ee9.jpg" width="50%"/>

### 转发到朋友圈后，在当前页面发截图即可。

提示：GitHub 的 issue 的可以编辑，上传图片时可以直接将图片拖拽到编辑框中进行上传。

如果上传遇到问题，还可以使用外链，markdown 图片格式如下：
```md
![随便写](http://图片地址.jpg)
```
还可以使用`<img/>`标签，可以控制图片大小：
```html
<img src="http://图片地址.jpg" width="50%"/>
```

### 大家在参与活动同时，还可以收藏下面几个项目
- MyBatis：https://github.com/mybatis/mybatis-3
- 分页插件 PageHelper：https://github.com/pagehelper/Mybatis-PageHelper
- 通用 Mapper：https://github.com/abel533/Mapper
- Spring 集成：https://github.com/abel533/Mybatis-Spring
- Spring Boot 集成：https://github.com/abel533/MyBatis-Spring-Boot

### 简单的抽奖代码
```java
import java.util.*;

/**
 * @author liuzh
 * @since 2017/7/5.
 */
public class Lottery {

    public static void main(String[] args) {
        int nums = 2;
        String[] users = new String[]{
                "test0", "test1", "test2", "test3", "test4", "test5", "test6", "test7", "test8", "test9",
                "test10", "test11", "test12", "test13", "test14", "test15", "test16", "test17", "test18", "test19",
                "test20", "test21", "test22", "test23", "test24", "test25", "test26", "test27", "test28", "test29",
                "test30", "test31", "test32", "test33", "test34", "test35", "test36", "test37", "test38", "test39",
                "test40", "test41", "test42", "test43", "test44", "test45", "test46", "test47", "test48", "test49",
        };
        lottery(users, nums);
    }

    public static void lottery(String[] users, int nums){
        List<String> userList = Arrays.asList(users);
        //乱序
        Collections.shuffle(userList);
        Random random = new Random();
        int i = 0;
        Set<Integer> set = new HashSet<>(nums);
        do {
            int nextInt = random.nextInt(userList.size());
            if(!set.contains(nextInt)){
                set.add(nextInt);
                i++;
            }
        } while (i < nums);
        System.out.println("============中奖名单============");
        for (Integer num : set) {
            System.out.println(userList.get(num));
        }
    }

}

```

**Comment by lzysuqianqiu** [comment]
转发就送？

**Comment by lzysuqianqiu** [comment]
已转发到朋友圈了
http://i1.buimg.com/1949/44cdf020f5ea57e7.png 外链

**Comment by abel533** [comment]
@lzysuqianqiu 不是转发就送，随机抽取。

**Comment by BruceKellan** [comment]
![Uploading Screenshot_2017-06-30-21-11-43.png…]()

**Comment by changhe626** [comment]
![screenshot_2017-06-30-21-12-30-072_com tencent mm](https://user-images.githubusercontent.com/25704942/27736961-f78d748c-5dd8-11e7-8c19-d99dedf58eb3.png)
分页插件真心的好用哦,感谢分享

**Comment by nanzhang237420759** [comment]
![wechatimg1](https://user-images.githubusercontent.com/3528634/27736995-14eba21a-5dd9-11e7-9ea5-b5ad9d656cff.jpeg)
支持支持

**Comment by BruceKellan** [comment]
![screenshot_2017-06-30-21-11-43](https://user-images.githubusercontent.com/13477122/27737006-1da43d04-5dd9-11e7-8a46-8e8b1a2a1410.png)

**Comment by usermanewhy** [comment]
<img src="
http://mgxq.oss-cn-shanghai.aliyuncs.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20170630211200.jpg" width="50%"/>

**Comment by usermanewhy** [comment]
<img src="
http://mgxq.oss-cn-shanghai.aliyuncs.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20170630211200.jpg" width="100%"/>

**Comment by jackmanwu** [comment]
![img_20170630_211926](https://user-images.githubusercontent.com/4475841/27737244-091d753e-5dda-11e7-9c05-7df7f83e13c5.jpg)

**Comment by xty805007911** [comment]
![default](https://user-images.githubusercontent.com/29798599/27737442-c1a30862-5dda-11e7-8d88-92d227d14d50.png)

**Comment by tianranll** [comment]
![img_0877](https://user-images.githubusercontent.com/29091772/27737462-d5ca14ca-5dda-11e7-92cb-fcd4221a7cbc.PNG)

**Comment by qq383264679** [comment]
![111](https://user-images.githubusercontent.com/5456250/27737603-4b0407fa-5ddb-11e7-9cfb-fb09373c0a15.png)

**Comment by drtrang** [comment]
已转发，通用Mapper重度使用者
![_20170630214656](https://user-images.githubusercontent.com/13851701/27738407-d668f448-5ddd-11e7-8b57-75c392283189.jpg)

**Comment by lvtao320** [comment]
准JAVAer,现已入坑Spring
![img_3026](https://user-images.githubusercontent.com/3281114/27739569-a5eac126-5de1-11e7-875b-94deedae74af.png)

**Comment by song-song** [comment]
![screenshot_2017-06-30-22-18-01](https://user-images.githubusercontent.com/13652906/27740026-2d3f907e-5de3-11e7-9639-9072dfca6841.png)

**Comment by raodoudou321** [comment]
支持一下作者!
![4544444444444444444](https://user-images.githubusercontent.com/3389198/27741117-a5b9044c-5de6-11e7-8f7b-cb86a3d6f24a.jpg)

**Comment by OrangesHuang** [comment]
![wechatimg15](https://user-images.githubusercontent.com/13177793/27741766-c3ba2168-5de8-11e7-91ff-9f35f32cf9a4.png)

**Comment by litttlefisher** [comment]
![图片](http://wx1.sinaimg.cn/mw690/7dde05d2gy1fh4g5jpbtcj20ku11219t.jpg)

**Comment by arvinsir** [comment]
![qq 20170702005432](https://user-images.githubusercontent.com/12154767/27763982-4f74900c-5ec1-11e7-90f3-9283e28af661.jpg)

**Comment by iHelin** [comment]
![img_0292](https://user-images.githubusercontent.com/16068212/27766859-1d9d9c34-5f13-11e7-98a5-d1e8fa56970b.PNG)

**Comment by penelopeWu** [comment]
![86977578092236374](https://user-images.githubusercontent.com/18033358/27767707-1cfdfd2c-5f32-11e7-8948-924252becbde.jpg)

**Comment by anjingdemutou** [comment]
![qq 20170703093423](https://user-images.githubusercontent.com/26755266/27775253-fb691dc6-5fd2-11e7-8b09-ba72755cb7bd.png)

**Comment by anjingdemutou** [comment]
![s70703-09330369](https://user-images.githubusercontent.com/26755266/27776111-63227460-5fda-11e7-91ad-ddde75913ece.jpg)

**Comment by tjj006** [comment]
![一定要支持一下！](https://user-images.githubusercontent.com/1046621/27776261-b417234c-5fdb-11e7-9379-e76f9c973435.png)

**Comment by tjj006** [comment]
![1123](https://user-images.githubusercontent.com/1046621/27776298-006eb49e-5fdc-11e7-9ed6-9584d439a1cd.jpeg)

**Comment by JavaerZJM** [comment]
![image](https://user-images.githubusercontent.com/15335682/27778357-d000e9b0-5fec-11e7-86db-fd6506e085f9.png)

**Comment by zhenggaojia** [comment]
![Uploading 290018400111705779.jpg…]()

**Comment by zhenggaojia** [comment]
![290018400111705779](https://user-images.githubusercontent.com/28640601/27783663-ad0c61ba-6009-11e7-822d-41b3a673b34d.jpg)

**Comment by yang1018679** [comment]
![_20170703162502](https://user-images.githubusercontent.com/19184958/27784263-33fcdb08-600c-11e7-9616-7f50bf452d22.jpg)

**Comment by LeeAfei0** [comment]
![Markdown](http://i1.buimg.com/599454/22e7baf9ca96b4d2.jpg)

**Comment by JoeyBling** [comment]
<img src='http://img.027cgb.cn/20170704/2017749681775731906.png' />

**Comment by easyfeng** [comment]
<img src="http://chuantu.biz/t5/125/1499139780x3682618338.jpg" width="50%"/>

**Comment by JoeyBling** [comment]
<img src="https://raw.githubusercontent.com/JoeyBling/JoeyBling.github.io/master/flag.png" width="100%"/>

**Comment by ChanceZhaoquanfeng** [comment]
<img src="https://user-images.githubusercontent.com/25545455/27814604-33674594-60b0-11e7-8696-bbc564fc4868.jpg" width="50%"/>

**Comment by wang3shi** [comment]
![s70704-113710](https://user-images.githubusercontent.com/29880480/27815052-dfb720aa-60b3-11e7-89cf-ee2f27b2fa6d.jpg)

**Comment by LuckyWind2157** [comment]
支持作者~~
![_20170704150257](https://user-images.githubusercontent.com/15851816/27818833-0eb68006-60ca-11e7-83c3-3f99fec81bcb.png)

**Comment by 1543453892** [comment]
![539124285120910284](https://user-images.githubusercontent.com/18655151/27835714-c13d4360-610e-11e7-8dc7-b40ad93d5940.jpg)
支持！想书！！！

**Comment by Jiellll** [comment]
我想请教下，在继承的mapper接口类或者其中方法里面，增加自定义注解，在mybatis的插件拦截里面能否取出注解并做自定义业务吗？

**Comment by huangfengyi** [comment]
求送书

**Comment by EchoXml** [comment]
![screenshot_2017-07-05-22-05-03-589_](https://user-images.githubusercontent.com/20317303/27868144-687c51ec-61ce-11e7-8434-ddbf93afaa90.png)

**Comment by luodonger** [comment]
支持

**Comment by luodonger** [comment]
` 感谢作者，好几个项目都有用到，期待好运
![img_1008](https://user-images.githubusercontent.com/6228242/27870288-1462aeba-61d5-11e7-9456-4b3dd4f18c9d.PNG)

**Comment by vanlin** [comment]
![qq 20170705225922](https://user-images.githubusercontent.com/983627/27870489-8b3a892c-61d5-11e7-8e10-032755f70ebc.png)

支持，学好MyBtais....

**Comment by easyfeng** [comment]
<img src=http://chuantu.biz/t5/127/1499268296x1971855313.png />

**Comment by GitHubBling** [comment]
<img src="https://raw.githubusercontent.com/GitHubBling/test/master/Screenshot_2017-07-06-08-54-11-786_com.tencent.mm.png" />

**Comment by abel533** [comment]
活动已经结束，等待开奖。
