### ISSUE TITLE
请问再插入的时候如何忽略主键 

### ISSUE THREAD

**Issue by guoliang3** [mybatis-book/book#55]
INSERT INTO country ( Id,countryname,countrycode ) VALUES( NULL,1,2 )
变成 

INSERT INTO country ( countryname,countrycode ) VALUES( 1,2 )

但是查询的时候 主键还需要正常显示 不能加@Transient

**Comment by abel533** [comment]
`@Column(insertable=false)` 即可。

**Comment by guoliang3** [comment]
update 如果这样的话  updatable=false 这样看样子也可以

UPDATE country  SET Id = Id,countryname = 3333,countrycode = 4444 WHERE  Id = 2

UPDATE country  SET countryname = 222,countrycode = 111 WHERE  Id = 2

**Comment by abel533** [comment]
不能加 @Transient
