### ISSUE TITLE
关于未使用通用mapper的旧项目换用通用mapper后的问题

### ISSUE THREAD

**Issue by Stel000** [mybatis-book/book#56]
#### 我想请问一下，当我不改动mbg的其他配置值也就是context下targetRuntime为MyBatis3时加入

```
<plugin type="tk.mybatis.mapper.generator.MapperPlugin">
	<property name="mappers" value="tk.mybatis.mapper.common.Mapper"/>
	<property name="caseSensitive" value="false"/>
	<property name="forceAnnotation" value="true"/>
</plugin>
```

#### 然后我的mapper生成配置如下:

```
<javaClientGenerator targetPackage="${targetMapperPackage}"
	 targetProject="${targetJavaProject}" type="ANNOTATEDMAPPER" />
```

#### 此时他不会生成SqlProvider。因为并非一开始项目就是用通用mapper，后面才加上的。我需要使用通用mapper的插件才能生成带注解的model从而正常查询，但因为项目有部分还没进行修改，我仍需要生成example和mapper保证旧逻辑不出错，同时项目的其他人不希望使用xml分离的做法，这种情况有办法解决吗？

**Comment by abel533** [comment]
这种情况就别配置Mapper插件了，正常生成代码后手动改 Mapper 接口。
